version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Installing dependencies...
      -
  build:
    commands:
      - echo Build started on `date`
      - echo Building Queue Agent...
      - docker build -t $AGENT_IMAGE_REPO_NAME:$IMAGE_TAG src/queue_agent/
      - docker tag $AGENT_IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AGENT_IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Building SD Web UI...
      - docker build -t $SDWEBUI_IMAGE_REPO_NAME:$IMAGE_TAG src/sd_webui_api/
      - docker tag $SDWEBUI_IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$SDWEBUI_IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$SDWEBUI_IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AGENT_IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Generating EBS snapshot...
      - utils/bottlerocket-image-cache/snapshot.sh -q $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$SDWEBUI_IMAGE_REPO_NAME:$IMAGE_TAG,$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AGENT_IMAGE_REPO_NAME:$IMAGE_TAG