stackName: "SdOnEks"
modelBucketArn: 'arn:aws:s3:::dummy-bucket'
modelsRuntime:
- name: "sdruntime"
  namespace: "default"
  modelFilename: "v1-5-pruned-emaonly.safetensors"
dynamicModelRuntime:
  enabled: true
  namespace: "default"