apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 2Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-webui-inference-api
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sd-webui-inference-api
  template:
    metadata:
      labels:
        app: sd-webui-inference-api
    spec:
      serviceAccountName: sd-webui-sa
      terminationGracePeriodSeconds: 0
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: efs-claim
      containers:
      - name: sd-webui-inference-api
        image: 057313215210.dkr.ecr.us-west-2.amazonaws.com/stable-diffusion-webui/inference-api:0.1.0
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /tmp/models
          name: models
        startupProbe:
          httpGet:
            path: /sdapi/v1/memory
            port: 8080
          failureThreshold: 120
          periodSeconds: 1
      - name: sd-webui-queue-agent
        image: 057313215210.dkr.ecr.us-west-2.amazonaws.com/stable-diffusion-webui/queue-agent:latest
        env:
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: SQS_QUEUE_URL
          value: https://sqs.us-west-2.amazonaws.com/057313215210/SdOnEksDataPlaneSandbox-eksClusterInputQueue19310EEB5-yK9YLbLTv5rI
        - name: S3_BUCKET
          value: sdoneksdataplanesandbox-eksclustersdoutputpdx31c2-2e684zsv4h1n
        - name: SNS_TOPIC_ARN
          value: arn:aws:sns:us-west-2:057313215210:SdOnEksDataPlaneSandbox-eksClustersdnotificationpdx1BF5B43B-D0FaamuF2rIt
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=SDWebUI
        - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
          value: urllib3
        - name: OTEL_PYTHON_ID_GENERATOR
          value: xray
        - name: OTEL_PROPAGATORS
          value: xray
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector-xray-collector:4317
        volumeMounts:
        - mountPath: /tmp/models
          name: models
          