apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gpu
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["g5.2xlarge"]
  taints:
    - key: nvidia.com/gpu
      effect: "NoSchedule"
  limits:
    resources:
      gpu: 100
  providerRef:
    name: gpu
  consolidation:
    enabled: true
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: gpu
spec:
  subnetSelector:
    Name: "SdOnEksDataPlaneSandbox/eksClusterStack/eksClusterStack-vpc/PrivateSubnet*"
  securityGroupSelector:
    "kubernetes.io/cluster/eksClusterStack": "owned"
  amiFamily: "Bottlerocket"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 10Gi
        volumeType: gp3
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 80Gi
        volumeType: gp3
        iops: 4000
        throughput: 1000
        deleteOnTermination: true
        snapshotID: snap-080513d57bfb8fc4a
        